### PR TITLE
Replace bunyan with winston 

### LINKED ISSUE #212: Bunyan dependency install complains loudly on windows with no python
```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\IEUser\Dev\ttt\node_modules\dtrace-provider
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

Consider replacing with a different package or using `-s` silent flag for npm install.

### PR DESCRIPTION
**Pull request by vogre**
No longer require binary dtrace-provider dependency
Include pid in logs
Update log name
Fixes #212

### CODE REVIEW

File: local-proxy/src/stdio.ts [hunk 1]
```diff
@@ -64,19 +63,20 @@ function uncaughtHandler(err: any) {
...
-        rotateExisting: false, // Give ourselves a clean file when we start up, based on period
-        threshold: '10m',      // Rotate log files larger than 10 megabytes
-        totalSize: '20m',      // Don't keep more than 20mb of archived log files
-        gzip: false,           // Compress the archive log files to save space
+  const logger = winston.createLogger({
+    format: winston.format.combine(
+      winston.format.timestamp(),
+      winston.format.json(),
+    ),
+    defaultMeta: { pid: process.pid },
```
Comment (arielshaqed) [inline local-proxy/src/stdio.ts]: Nice & useful!
